//! Friends this instance shares with.
//!
//! Each peer holds a key it presents on every Torznab request. Only a SHA-256 of
//! that key is stored — see the header of `migrations/0003_peers.sql` for why a
//! fast hash is the right choice here and Argon2 is not, and why this lives in
//! SQLite rather than the vault.
//!
//! The key itself is generated by the caller (`sharerr`'s `secrets` module), not
//! here: this crate has no opinion about how long a bearer token should be, and the
//! same generator already mints the Torznab and tracker secrets.

use secrecy::{ExposeSecret, SecretString};
use sha2::{Digest, Sha256};
use sqlx::Row;

use crate::db::{Store, StoreError, now_epoch};

type Result<T> = std::result::Result<T, StoreError>;

/// One friend, as the UI lists them. Never carries the key — it cannot, and that
/// is the point.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Peer {
    pub id: i64,
    pub label: String,
    pub created_at: i64,
    /// When this peer last made an authenticated request, or `None` if never.
    pub last_seen_at: Option<i64>,
    /// When the key was revoked, or `None` while it still works.
    pub revoked_at: Option<i64>,
}

impl Peer {
    pub fn is_revoked(&self) -> bool {
        self.revoked_at.is_some()
    }
}

/// Lowercase hex SHA-256, the form stored in `peers.key_hash`.
///
/// Free function rather than a method so the lookup and the insert cannot disagree
/// about the encoding — a mismatch there would present as "the key I just issued
/// does not work", with nothing in the logs.
fn hash_key(key: &SecretString) -> String {
    let digest = Sha256::digest(key.expose_secret().as_bytes());
    // `{:02x}` per byte rather than a helper crate: this is the only place in the
    // workspace that needs it, and the encoding is load-bearing enough to be
    // visible.
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn validate_label(label: &str) -> Result<String> {
    let trimmed = label.trim();
    if trimmed.is_empty() {
        return Err(StoreError::InvalidUser("a peer needs a name"));
    }
    if trimmed.chars().count() > 64 {
        return Err(StoreError::InvalidUser(
            "a peer name must be 64 characters or fewer",
        ));
    }
    Ok(trimmed.to_owned())
}

fn row_to_peer(row: &sqlx::sqlite::SqliteRow) -> Result<Peer> {
    Ok(Peer {
        id: row.try_get("id")?,
        label: row.try_get("label")?,
        created_at: row.try_get("created_at")?,
        last_seen_at: row.try_get("last_seen_at")?,
        revoked_at: row.try_get("revoked_at")?,
    })
}

impl Store {
    /// Record a new peer holding `key`.
    ///
    /// The key is consumed as a `SecretString` and only its hash is kept, so the
    /// caller is the last thing that can show it to anybody. That is deliberate:
    /// the UI reveals it once on the response that created it and never again.
    pub async fn create_peer(&self, label: &str, key: &SecretString) -> Result<Peer> {
        let label = validate_label(label)?;
        let now = now_epoch();

        // The UNIQUE constraint decides this, not a prior SELECT — two submissions
        // racing would both pass a check-then-insert.
        let row = sqlx::query(
            "INSERT INTO peers (label, key_hash, created_at) VALUES (?1, ?2, ?3) \
             RETURNING id, label, created_at, last_seen_at, revoked_at",
        )
        .bind(&label)
        .bind(hash_key(key))
        .bind(now)
        .fetch_one(self.pool())
        .await
        .map_err(|err| match &err {
            sqlx::Error::Database(db) if db.is_unique_violation() => StoreError::UserExists {
                username: label.clone(),
            },
            _ => StoreError::Sql(err),
        })?;

        row_to_peer(&row)
    }

    /// Every peer, newest first, revoked ones included.
    ///
    /// Revoked peers stay in the list on purpose: "I revoked Sam last week" is
    /// something an operator needs to be able to see, and a row that vanishes looks
    /// like a bug.
    pub async fn list_peers(&self) -> Result<Vec<Peer>> {
        let rows = sqlx::query(
            "SELECT id, label, created_at, last_seen_at, revoked_at FROM peers \
             ORDER BY created_at DESC, id DESC",
        )
        .fetch_all(self.pool())
        .await?;

        rows.iter().map(row_to_peer).collect()
    }

    /// The active peer holding `key`, if any.
    ///
    /// One indexed equality lookup regardless of how many peers exist — the reason
    /// the stored hash is a fast one. A revoked peer is `None`: the row is kept for
    /// the operator's benefit, not to keep letting its key in.
    pub async fn peer_by_key(&self, key: &SecretString) -> Result<Option<Peer>> {
        let row = sqlx::query(
            "SELECT id, label, created_at, last_seen_at, revoked_at FROM peers \
             WHERE key_hash = ?1 AND revoked_at IS NULL",
        )
        .bind(hash_key(key))
        .fetch_optional(self.pool())
        .await?;

        row.as_ref().map(row_to_peer).transpose()
    }

    /// Note that a peer just made an authenticated request.
    ///
    /// Deliberately not part of `peer_by_key`: a read that writes would make the
    /// authentication path take a write lock on every single query. The caller
    /// decides when it is worth recording.
    pub async fn touch_peer(&self, id: i64) -> Result<()> {
        sqlx::query("UPDATE peers SET last_seen_at = ?1 WHERE id = ?2")
            .bind(now_epoch())
            .bind(id)
            .execute(self.pool())
            .await?;
        Ok(())
    }

    /// Stop honouring a peer's key. Returns whether anything changed.
    ///
    /// Idempotent: revoking an already-revoked peer returns `false` rather than
    /// moving the timestamp, so the record of *when* access was cut stays true.
    pub async fn revoke_peer(&self, id: i64) -> Result<bool> {
        let affected =
            sqlx::query("UPDATE peers SET revoked_at = ?1 WHERE id = ?2 AND revoked_at IS NULL")
                .bind(now_epoch())
                .bind(id)
                .execute(self.pool())
                .await?
                .rows_affected();
        Ok(affected > 0)
    }

    /// Remove a peer entirely, freeing its label for reuse.
    pub async fn delete_peer(&self, id: i64) -> Result<bool> {
        let affected = sqlx::query("DELETE FROM peers WHERE id = ?1")
            .bind(id)
            .execute(self.pool())
            .await?
            .rows_affected();
        Ok(affected > 0)
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    async fn store() -> Store {
        Store::open_in_memory()
            .await
            .expect("in-memory store opens")
    }

    fn key(value: &str) -> SecretString {
        SecretString::from(value)
    }

    #[tokio::test]
    async fn a_peer_round_trips_and_is_found_by_its_key() {
        let store = store().await;
        let created = store
            .create_peer("Sam", &key("peer-key-one"))
            .await
            .unwrap();

        assert_eq!(created.label, "Sam");
        assert_eq!(created.last_seen_at, None, "a new peer has never been seen");
        assert!(!created.is_revoked());

        let found = store
            .peer_by_key(&key("peer-key-one"))
            .await
            .unwrap()
            .expect("the issued key must authenticate");
        assert_eq!(found.id, created.id);
    }

    #[tokio::test]
    async fn a_key_nobody_was_issued_matches_nothing() {
        let store = store().await;
        store
            .create_peer("Sam", &key("peer-key-one"))
            .await
            .unwrap();

        assert!(store.peer_by_key(&key("guessed")).await.unwrap().is_none());
    }

    /// The whole reason peers exist: one friend can be cut off without touching
    /// anybody else. Under the old single shared key this was not expressible.
    #[tokio::test]
    async fn revoking_one_peer_leaves_the_others_working() {
        let store = store().await;
        let sam = store.create_peer("Sam", &key("sam-key")).await.unwrap();
        store.create_peer("Alex", &key("alex-key")).await.unwrap();

        assert!(store.revoke_peer(sam.id).await.unwrap());

        assert!(
            store.peer_by_key(&key("sam-key")).await.unwrap().is_none(),
            "a revoked key must stop working"
        );
        assert!(
            store.peer_by_key(&key("alex-key")).await.unwrap().is_some(),
            "revoking Sam must not affect Alex"
        );
    }

    /// The row survives revocation so the operator can still see it happened.
    #[tokio::test]
    async fn a_revoked_peer_is_still_listed() {
        let store = store().await;
        let sam = store.create_peer("Sam", &key("sam-key")).await.unwrap();
        store.revoke_peer(sam.id).await.unwrap();

        let listed = store.list_peers().await.unwrap();
        assert_eq!(listed.len(), 1);
        assert!(listed[0].is_revoked());
    }

    /// Revoking twice must not move the timestamp — when access was cut is a fact.
    #[tokio::test]
    async fn revoking_is_idempotent() {
        let store = store().await;
        let sam = store.create_peer("Sam", &key("sam-key")).await.unwrap();

        assert!(store.revoke_peer(sam.id).await.unwrap());
        assert!(
            !store.revoke_peer(sam.id).await.unwrap(),
            "a second revoke changes nothing"
        );
    }

    #[tokio::test]
    async fn last_seen_starts_empty_and_is_recorded_on_demand() {
        let store = store().await;
        let sam = store.create_peer("Sam", &key("sam-key")).await.unwrap();
        assert_eq!(sam.last_seen_at, None);

        store.touch_peer(sam.id).await.unwrap();

        let listed = store.list_peers().await.unwrap();
        assert!(
            listed[0].last_seen_at.is_some(),
            "a touched peer must show a last-seen time"
        );
    }

    #[tokio::test]
    async fn two_peers_cannot_share_a_label() {
        let store = store().await;
        store.create_peer("Sam", &key("one")).await.unwrap();

        let err = store.create_peer("Sam", &key("two")).await;
        assert!(matches!(err, Err(StoreError::UserExists { .. })), "{err:?}");
    }

    #[tokio::test]
    async fn a_blank_label_is_refused() {
        let store = store().await;
        let err = store.create_peer("   ", &key("one")).await;
        assert!(matches!(err, Err(StoreError::InvalidUser(_))), "{err:?}");
    }

    #[tokio::test]
    async fn deleting_a_peer_frees_its_label() {
        let store = store().await;
        let sam = store.create_peer("Sam", &key("one")).await.unwrap();

        assert!(store.delete_peer(sam.id).await.unwrap());
        assert!(store.list_peers().await.unwrap().is_empty());
        // The label is reusable again, which is what distinguishes delete from
        // revoke.
        store.create_peer("Sam", &key("two")).await.unwrap();
    }

    #[tokio::test]
    async fn deleting_something_that_is_not_there_reports_it() {
        let store = store().await;
        assert!(!store.delete_peer(404).await.unwrap());
    }

    /// The stored value must not be the key. Anyone reading the database file must
    /// not come away able to authenticate as a friend.
    #[tokio::test]
    async fn the_key_itself_is_never_stored() {
        let store = store().await;
        store
            .create_peer("Sam", &key("SUPERSECRETPEERKEY"))
            .await
            .unwrap();

        let row = sqlx::query("SELECT key_hash FROM peers")
            .fetch_one(store.pool())
            .await
            .unwrap();
        let stored: String = row.try_get("key_hash").unwrap();

        assert_ne!(stored, "SUPERSECRETPEERKEY");
        assert!(!stored.contains("SUPERSECRET"));
        assert_eq!(stored.len(), 64, "hex SHA-256 is 64 characters");
        assert!(stored.chars().all(|c| c.is_ascii_hexdigit()));
    }
}
