[package]
name = "sharerr-qbit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
reqwest = { version = "0.13.4", default-features = false, features = ["json", "query", "form", "rustls", "http2", "charset", "multipart", "cookies"] }
secrecy = "0.10.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sharerr-core = { version = "0.1.0", path = "../sharerr-core" }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt", "macros", "sync"] }
tracing = "0.1.44"
url = "2.5.8"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
wiremock = "0.6.5"
