//! `sharerr openapi` — print the generated API document.
//!
//! Deliberately trivial: everything interesting is in [`crate::openapi`], and
//! this exists so the document can be regenerated by anyone with the binary,
//! without a running instance behind it.

use std::path::Path;

use anyhow::{Context, Result};

pub fn run(output: Option<&Path>) -> Result<()> {
    let json = crate::openapi::to_json().context("rendering the OpenAPI document")?;

    match output {
        Some(path) => {
            // A trailing newline, because this is written to a file that lands
            // in git and a missing one shows up as a diff on every tool that
            // adds it back.
            std::fs::write(path, format!("{json}\n"))
                .with_context(|| format!("writing {}", path.display()))?;
            tracing::info!(path = %path.display(), "wrote the OpenAPI document");
        }
        None => println!("{json}"),
    }
    Ok(())
}
