//! `sharerr openapi` — print the generated API document.
//!
//! Deliberately trivial: everything interesting is in [`crate::openapi`], and
//! this exists so the document can be regenerated by anyone with the binary,
//! without a running instance behind it.

use std::path::Path;

use anyhow::{Context, Result};

pub fn run(output: Option<&Path>) -> Result<()> {
    let json = crate::openapi::to_json().context("rendering the OpenAPI document")?;

    match output {
        Some(path) => {
            // A trailing newline, because this is written to a file that lands
            // in git and a missing one shows up as a diff on every tool that
            // adds it back.
            std::fs::write(path, format!("{json}\n"))
                .with_context(|| format!("writing {}", path.display()))?;
            tracing::info!(path = %path.display(), "wrote the OpenAPI document");
        }
        None => println!("{json}"),
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    /// Also a guard on `crate::openapi` itself: the document is derived from
    /// the handlers, so a malformed `utoipa` annotation fails here rather than
    /// at the next release when somebody regenerates the file.
    #[test]
    fn writing_the_document_produces_parseable_json() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("openapi.json");

        run(Some(&path)).unwrap();

        let written = std::fs::read_to_string(&path).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&written).unwrap();
        assert!(parsed.get("openapi").is_some(), "{written}");
        assert!(parsed.get("paths").is_some(), "{written}");
    }

    /// The file lands in git, and a missing trailing newline shows up as a
    /// diff on every tool that adds one back -- which is why `run` appends it.
    #[test]
    fn the_written_document_ends_with_exactly_one_newline() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("openapi.json");

        run(Some(&path)).unwrap();

        let written = std::fs::read_to_string(&path).unwrap();
        assert!(written.ends_with('\n'), "no trailing newline");
        assert!(!written.ends_with("\n\n"), "more than one trailing newline");
    }

    /// An unwritable path has to surface as an error rather than a panic --
    /// this runs from a CLI where the operator chose the path.
    #[test]
    fn an_unwritable_path_is_reported_rather_than_panicking() {
        let dir = tempfile::tempdir().unwrap();
        // A directory that does not exist, so the create fails.
        let path = dir.path().join("nope").join("openapi.json");

        let err = run(Some(&path)).unwrap_err();

        assert!(
            err.to_string().contains("writing"),
            "expected the path in the context: {err}"
        );
    }
}
